import type { Metadata } from "next";
import { Titillium_Web } from "next/font/google";
import "./globals.css";

import { Providers } from "./providers";

const titillium = Titillium_Web({
  weight: ["200", "300", "400", "600", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`antialiased ${titillium.className}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
